---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-10.04
  driver_config:
    customize:
      memory: 1024
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
  run_list:
  - recipe[apt::cacher-client]
  - recipe[apt]

- name: ubuntu-12.04
  driver_config:
    customize:
      memory: 1024
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
  - recipe[apt::cacher-client]
  - recipe[apt]

- name: ubuntu-13.04
  driver_config:
    customize:
      memory: 1024
    box: opscode-ubuntu-13.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-13.04_provisionerless.box
  run_list:
  - recipe[apt::cacher-client]
  - recipe[apt]

# add once the bento image is fixed
# - name: debian-7.1
#   driver_config:
#     customize:
#       memory: 1024
#     box: opscode-debian-7.1
#     box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_debian-7.1.0_provisionerless.box
#   run_list:
#   - recipe[apt]

- name: centos-5.9
  driver_config:
    customize:
      memory: 1024
    box: opscode-centos-5.9
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box
  run_list:
  - recipe[yum::epel]

- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
  run_list:
  - recipe[yum::epel]

- name: fedora-18
  driver_config:
    customize:
      memory: 1024
    box: opscode-fedora-18
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode-fedora-18_provisionerless.box
  run_list:
  - recipe[rabbitmq]

# image not downloading
# - name: smartos-13.1
#   driver_config:
#     customize:
#       memory: 1024
#     box: smartos-base1310
#     box_url: http://dlc-int.openindiana.org/aszeszo/vagrant/smartos-base1310-64-virtualbox-20130806.box
#   run_list:
#   - recipe[rabbitmq]

# http://tickets.opscode.com/browse/COOK-2467
# - name: omnios-r151002
#   driver_config:
#     customize:
#       memory: 1024
#     box: omnios-r151002
#     box_url: http://omnios.omniti.com/media/omnios-latest.box
#   run_list:
#   - recipe[rabbitmq]

suites:
- name: default
  excludes:
  - omnios-r151002
  - smartos-13.1
  run_list:
  - recipe[minitest-handler]
  - recipe[rabbitmq_test::default]
  #attributes: {}
  attributes:
    apt:
      cacher_ipaddress: '192.168.1.10'

- name: upstart
  excludes:
  - centos-5.9
  - centos-6.4
  - fedora-18
  - omnios-r151002
  - smartos-13.1
  run_list:
  - recipe[minitest-handler]
  - recipe[rabbitmq_test::default]
  attributes:
    rabbitmq:
      job_control: 'upstart'
    apt:
      cacher_ipaddress: '192.168.1.10'

- name: distro-version
  excludes:
  - centos-5.9
  - fedora-18
  - ubuntu-10.04
  run_list:
  - recipe[minitest-handler]
  - recipe[rabbitmq_test::default]
  attributes:
    rabbitmq:
      use_distro_version: true
    apt:
      cacher_ipaddress: '192.168.1.10'

- name: mgmt_console
  run_list:
  - recipe[minitest-handler]
  - recipe[rabbitmq]
  - recipe[rabbitmq_test::mgmt_console]
  #attributes: {}
  attributes:
    apt:
      cacher_ipaddress: '192.168.1.10'

# - name: cook-2151
#   run_list:
#   - recipe[minitest-handler]
#   - recipe[rabbitmq]
#   - recipe[rabbitmq_test]
#   - recipe[rabbitmq_test::cook-2151]
#   attributes:
#     rabbitmq:
#       disk_free_limit_relative: 1.0
#       vm_memory_high_watermark: 0.5
#     apt:
#       cacher_ipaddress: '192.168.1.10'

# this is testing create and deletes with duplicates and nonexistant entries.
- name: all-management
  run_list:
  - recipe[rabbitmq::plugin_management]
  - recipe[rabbitmq::vhost_management]
  - recipe[rabbitmq::policy_management]
  - recipe[rabbitmq::user_management]
  #- recipe[rabbitmq_test::user_tests] # more deletes, tag, permissions
  attributes:
    apt:
      cacher_ipaddress: '192.168.1.10'
    rabbitmq:
      enabled_plugins: ["rabbitmq_stomp", "rabbitmq_shovel", "rabbitmq_stomp"]
      disabled_plugins: ["nonexistant_plugin", "rabbitmq_shovel"]
      enabled_users: [
      {name: "kitchen1", password: "test", tag: "tag1", rights: [{vhost: "kitchen", conf: ".*", write: ".*", read: ".*"}]},
      {name: "kitchen2", password: "test", tag: "tag2", rights: [{vhost: "kitchen", conf: ".*", write: ".*", read: ".*"}, {vhost: "kitchen", conf: ".*", write: ".*", read: ".*"}]},
      {name: "kitchen3", password: "test", tag: "tag3", rights: [{vhost: "kitchen", conf: ".*", write: ".*", read: ".*"}]},
      {name: "kitchen1", password: "test", tag: "tag4", rights: [{vhost: "kitchen", conf: ".*", write: ".*", read: ".*"}]}
      ]
      disabled_users: ["nonexistant_user", "kitchen2"]
      virtualhosts: ["kitchen", "kitchen"]
